#!/usr/bin/env node
// SPDX-License-Identifier: AGPL-3.0-or-later OR EUPL-1.2
// Copyright 2026 Saimonokuma.
//
// checker/badges.mjs [--check | --controls]
//
// Draws the two hosted-surface badges that head README.md. They are generated
// rather than fetched because the brief asks for a two-tone transition on each
// half, and a shields.io badge renders one flat colour per half: the gradient
// is the thing that could not be bought, so it is drawn here.
//
//   docs/badge-claude-ai.svg   claude.ai (orange) | Customize (purple)
//   docs/badge-cowork.svg      claude-cowork (green to orange) | Plugin (magenta to orange)
//
// Both link, from the README, to the hosted install section. The name on the
// badge is the instruction: a reader who already knows what Customize is does
// not need the tutorial, and a reader who does not gets it in one click.
//
// --check   regenerate into memory and refuse a file on disk that differs
// --controls trip every guard on purpose; exit 1 if one stays silent

import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'node:fs';
import { join, dirname } from 'node:path';

const ROOT = join(dirname(new URL(import.meta.url).pathname.replace(/^\/([A-Za-z]:)/, '$1')), '..');
const OUT = join(ROOT, 'docs');
const LF = String.fromCharCode(10);

// A width table for 11px bold DejaVu Sans, the face every SVG renderer on
// GitHub falls back to. Estimating one average width makes short labels sit
// crooked inside their panel, which is visible at this size, so the narrow and
// the wide glyphs are named.
const NARROW = new Set(['i', 'j', 'l', 't', 'f', 'I', '.', ',', ':', ';', "'", '|', '!', '(', ')', '[', ']', '-']);
const WIDE = new Set(['m', 'w', 'M', 'W', '@', '%']);
function textWidth(s) {
  let w = 0;
  for (const ch of s) w += NARROW.has(ch) ? 4.2 : WIDE.has(ch) ? 10.4 : ch === ' ' ? 3.6 : 7.15;
  return Math.ceil(w);
}

const PAD = 13;
const H = 30;

function esc(s) {
  return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}

// One badge: two panels, each filled with its own left-to-right gradient.
function badge({ id, left, right, leftFrom, leftTo, rightFrom, rightTo, alt }) {
  const lw = textWidth(left) + PAD * 2;
  const rw = textWidth(right) + PAD * 2;
  const w = lw + rw;
  const L = [];
  // Every file in this tree carries its licence; the gate refuses one that
  // does not, and it refused these two on their first run.
  L.push(`<?xml version="1.0" encoding="UTF-8"?>`);
  L.push(`<!-- SPDX-License-Identifier: AGPL-3.0-or-later OR EUPL-1.2 -->`);
  L.push(`<!-- Copyright 2026 Saimonokuma. GENERATED by checker/badges.mjs. -->`);
  L.push(`<svg xmlns="http://www.w3.org/2000/svg" width="${w}" height="${H}" viewBox="0 0 ${w} ${H}" role="img" aria-label="${esc(alt)}">`);
  L.push(`  <title>${esc(alt)}</title>`);
  L.push('  <defs>');
  L.push(`    <linearGradient id="${id}-l" x1="0" y1="0" x2="1" y2="0">`);
  L.push(`      <stop offset="0" stop-color="${leftFrom}"/><stop offset="1" stop-color="${leftTo}"/>`);
  L.push('    </linearGradient>');
  L.push(`    <linearGradient id="${id}-r" x1="0" y1="0" x2="1" y2="0">`);
  L.push(`      <stop offset="0" stop-color="${rightFrom}"/><stop offset="1" stop-color="${rightTo}"/>`);
  L.push('    </linearGradient>');
  // A single rounded clip over both panels, so the seam between them stays
  // square while the outer corners round.
  L.push(`    <clipPath id="${id}-c"><rect width="${w}" height="${H}" rx="4"/></clipPath>`);
  L.push('  </defs>');
  L.push(`  <g clip-path="url(#${id}-c)">`);
  L.push(`    <rect width="${lw}" height="${H}" fill="url(#${id}-l)"/>`);
  L.push(`    <rect x="${lw}" width="${rw}" height="${H}" fill="url(#${id}-r)"/>`);
  L.push(`    <rect width="${w}" height="${H}" fill="#000" opacity="0.06"/>`);
  L.push(`    <rect width="${w}" height="1" fill="#fff" opacity="0.18"/>`);
  L.push('  </g>');
  L.push(`  <g font-family="Verdana,DejaVu Sans,Geneva,sans-serif" font-size="11" font-weight="700" text-anchor="middle" letter-spacing="0.6">`);
  // The shadow line under each label is what keeps light text legible on the
  // lighter end of a gradient; a flat badge does not need it and this one does.
  L.push(`    <text x="${(lw / 2).toFixed(1)}" y="${H / 2 + 5}" fill="#000" opacity="0.28">${esc(left)}</text>`);
  L.push(`    <text x="${(lw / 2).toFixed(1)}" y="${H / 2 + 4}" fill="#fff">${esc(left)}</text>`);
  L.push(`    <text x="${(lw + rw / 2).toFixed(1)}" y="${H / 2 + 5}" fill="#000" opacity="0.28">${esc(right)}</text>`);
  L.push(`    <text x="${(lw + rw / 2).toFixed(1)}" y="${H / 2 + 4}" fill="#fff">${esc(right)}</text>`);
  L.push('  </g>');
  L.push('</svg>');
  return L.join(LF) + LF;
}

export const BADGES = {
  'badge-claude-ai.svg': {
    id: 'ca',
    left: 'claude.ai',
    right: 'Customize',
    // D97757 is the Anthropic orange this README already uses for the Claude
    // Code badge, and 764ba2 the purple of its License badge: the new pair
    // reads as part of the existing row rather than a sticker on top of it.
    leftFrom: '#D97757',
    leftTo: '#F0916B',
    rightFrom: '#764ba2',
    rightTo: '#9B6FD4',
    alt: 'claude.ai Customize: drag the release archive into Customize',
  },
  'badge-cowork.svg': {
    id: 'cw',
    left: 'claude-cowork',
    right: 'Plugin',
    leftFrom: '#2FBF71',
    leftTo: '#F5A623',
    rightFrom: '#E0218A',
    rightTo: '#F5691E',
    alt: 'Claude Cowork Plugin: the same archive installs on the desktop app',
  },
};

export function render() {
  const out = {};
  for (const [file, spec] of Object.entries(BADGES)) out[file] = badge(spec);
  return out;
}

function write() {
  if (!existsSync(OUT)) mkdirSync(OUT, { recursive: true });
  const made = render();
  let n = 0;
  for (const [file, svg] of Object.entries(made)) {
    const p = join(OUT, file);
    const had = existsSync(p) ? readFileSync(p, 'utf8') : null;
    if (had !== svg) { writeFileSync(p, svg, 'utf8'); n++; }
    console.log(`  ${file}  ${svg.length} bytes${had === svg ? '' : '  written'}`);
  }
  console.log(`badges: ${Object.keys(made).length} drawn, ${n} changed`);
  return 0;
}

function check() {
  const made = render();
  const drift = [];
  for (const [file, svg] of Object.entries(made)) {
    const p = join(OUT, file);
    if (!existsSync(p)) { drift.push(`${file} is missing`); continue; }
    if (readFileSync(p, 'utf8') !== svg) drift.push(`${file} differs from a fresh render`);
  }
  for (const d of drift) console.log(`  DRIFT ${d}`);
  console.log(`badges --check: ${Object.keys(made).length} badges, ${drift.length} drifted`);
  return drift.length ? 1 : 0;
}

function controls() {
  const results = [];
  const run = (name, fn) => {
    let ok = false, detail = '';
    try { const r = fn(); ok = r.ok; detail = r.detail; } catch (e) { detail = `threw: ${e.message}`; }
    results.push({ name, ok, detail });
  };

  run('B1 both badges render as parseable SVG with a viewBox and a licence', () => {
    const made = render();
    const bad = Object.entries(made).filter(([, s]) =>
      !s.startsWith('<?xml version="1.0" encoding="UTF-8"?>') ||
      !s.includes('SPDX-License-Identifier:') ||
      !s.includes('<svg xmlns=') ||
      !s.includes('viewBox=') ||
      !s.trimEnd().endsWith('</svg>'));
    return { ok: bad.length === 0, detail: bad.length ? bad.map(([f]) => f).join(', ') : `${Object.keys(made).length} well formed and licensed` };
  });

  run('B2 every declared colour reaches the output', () => {
    const made = render();
    const missing = [];
    for (const [file, spec] of Object.entries(BADGES)) {
      for (const k of ['leftFrom', 'leftTo', 'rightFrom', 'rightTo']) {
        if (!made[file].includes(spec[k])) missing.push(`${file}:${k}`);
      }
    }
    return { ok: missing.length === 0, detail: missing.length ? missing.join(', ') : 'all eight stops present' };
  });

  run('B3 each badge carries two gradients, not one flat fill', () => {
    const made = render();
    const bad = Object.entries(made).filter(([, s]) => (s.match(/<linearGradient/g) || []).length !== 2);
    return { ok: bad.length === 0, detail: bad.length ? bad.map(([f]) => f).join(', ') : 'two gradients each, which is the reason these are not shields.io' };
  });

  run('B4 the panel is wider than its text (no clipped label)', () => {
    const bad = [];
    for (const [file, spec] of Object.entries(BADGES)) {
      const lw = textWidth(spec.left) + PAD * 2;
      const rw = textWidth(spec.right) + PAD * 2;
      if (lw <= textWidth(spec.left) || rw <= textWidth(spec.right)) bad.push(file);
      if (lw < 40 || rw < 40) bad.push(`${file} panel under 40px`);
    }
    return { ok: bad.length === 0, detail: bad.length ? bad.join(', ') : 'both panels have padding on each side' };
  });

  run('B5 --check goes red on a damaged file', () => {
    // The mutation is in memory: a check that cannot fail is decoration, and
    // proving it on disk would leave the repository dirty if this threw.
    const made = render();
    const p = join(OUT, 'badge-claude-ai.svg');
    if (!existsSync(p)) return { ok: false, detail: 'nothing on disk to compare against' };
    const onDisk = readFileSync(p, 'utf8');
    const damaged = onDisk.replace('#D97757', '#000000');
    if (damaged === onDisk) return { ok: false, detail: 'the mutation did not land: #D97757 is not in the file' };
    return { ok: damaged !== made['badge-claude-ai.svg'], detail: 'a changed stop is a difference --check reports' };
  });

  run('B6 the width table separates narrow, wide and default glyphs', () => {
    const i = textWidth('iii'), m = textWidth('mmm'), x = textWidth('xxx');
    return { ok: i < x && x < m, detail: `iii ${i} < xxx ${x} < mmm ${m}` };
  });

  for (const r of results) console.log(`${r.ok ? 'ok  ' : 'FAIL'} ${r.name} — ${r.detail}`);
  const failed = results.filter((r) => !r.ok).length;
  console.log(`${LF}${results.length} run, ${failed} failing`);
  return failed ? 1 : 0;
}

const arg = process.argv[2];
process.exit(arg === '--check' ? check() : arg === '--controls' ? controls() : write());
