#!/usr/bin/env node
// SPDX-License-Identifier: AGPL-3.0-or-later OR EUPL-1.2
// Copyright 2026 Saimonokuma.
//
// checker/plates.mjs
// The README's plates, drawn from the README and held to it. Seven sections
// (welcome, about, where, verify, contributing, supporting, licence) are
// shown as SVG plates, light and dark, and the claims table as a third pair.
// Until 9.0.0 the section plates were drawn once by a script that never
// entered the tree, and the claims plate named a renderer that did not
// exist, so both said what the README no longer said: the eighth companion
// pass measured thirty guards drawn against thirty-one, 131 commands
// against 139, and a README sentence promising that nothing was hidden the
// plate did not show. Now each section plate is rendered from a source
// block that sits in the README beside its picture, <!-- rdc-section:<name>
// ... -->, the claims plate from the rdc-claims rows, and --check holds every
// file to a fresh render the way checker/glossary.mjs holds its map.
//
//   node checker/plates.mjs              render the sixteen plates
//   node checker/plates.mjs --check      "N plates in step", or the drifted names and exit 1
//   node checker/plates.mjs --controls   eight controls, planted drift tripped
//
// Source block lines: prose wraps; a blank line ends a paragraph; ### opens
// a sub-heading; a fence line opens or closes a code block drawn in
// monospace, the fence itself never drawn; two leading spaces indent a
// line; --- draws a rule; <div align="center"> and </div> centre what they
// enclose. Inline code marks, bold stars and link brackets are stripped:
// the plate draws words, and a reader of the README sees the same words.

import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { join, dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
export const SECTIONS = ['welcome', 'about', 'where', 'verify', 'contributing', 'supporting', 'licence'];
const W = 820;
const LEFT = 26;
const RIGHT = 794;
const INDENT = 42;
const WRAP = 88;
const WRAP_CODE = 96;
const WRAP_CLAIM = 92;
const WRAP_INSTRUMENT = 86;
const FONT = '-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Helvetica,Arial,sans-serif';
const MONO = 'ui-monospace,SFMono-Regular,Menlo,Consolas,monospace';
export const THEMES = {
  light: { bg: '#ffffff', text: '#1a1d24', muted: '#5b6472', rule: '#e2e5ec', section: '#b8543a', claims: '#1a7f37' },
  dark: { bg: '#0f1117', text: '#e6e9ef', muted: '#9aa3b2', rule: '#242938', section: '#d97757', claims: '#3fb950' },
};

export const esc = (s) => String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
export const plain = (s) => String(s)
  .replace(/`([^`]*)`/g, '$1')
  .replace(/\*\*([^*]+)\*\*/g, '$1')
  .replace(/\[([^\]]+)\]\([^)]*\)/g, '$1')
  .replace(/&mdash;/g, '--')
  .replace(/\s+/g, ' ')
  .trim();

// Word wrap at a width in characters; a word longer than the width keeps a
// line of its own rather than being cut.
export function wrap(text, width) {
  const lines = [];
  let cur = '';
  for (const w of String(text).split(' ')) {
    if (!w) continue;
    if (!cur) cur = w;
    else if (cur.length + 1 + w.length <= width) cur += ' ' + w;
    else { lines.push(cur); cur = w; }
  }
  if (cur) lines.push(cur);
  return lines;
}

function svg(h, bg, bar, nodes) {
  return `<?xml version="1.0" encoding="UTF-8"?>
<!-- SPDX-License-Identifier: AGPL-3.0-or-later OR EUPL-1.2 -->
<!-- Copyright 2026 Saimonokuma. GENERATED by checker/plates.mjs from README.md; edit the README, then run node checker/plates.mjs. -->
<svg xmlns="http://www.w3.org/2000/svg" width="${W}" height="${h}" viewBox="0 0 ${W} ${h}" font-family="${FONT}">
<rect width="${W}" height="${h}" fill="${bg}"/>
<rect x="0" y="0" width="6" height="${h}" fill="${bar}"/>
${nodes.join('\n')}
</svg>
`;
}

// The README: every pictured section with the heading above its picture and
// the source block after it. A pictured section with no block is refused by
// name; a plate nobody can re-derive is the fault this file exists to end.
export function sources(readme) {
  const out = {};
  const pic = /<img alt="[^"]*" src="docs\/section-([a-z]+)\.svg" \/>/g;
  let m;
  while ((m = pic.exec(readme))) {
    const name = m[1];
    const heads = [...readme.slice(0, m.index).matchAll(/^## .*$/gm)];
    const heading = heads.length ? heads[heads.length - 1][0].trim() : '';
    const open = readme.indexOf(`<!-- rdc-section:${name}`, m.index);
    const close = open < 0 ? -1 : readme.indexOf('-->', open);
    if (open < 0 || close < 0) throw new Error(`plates: the README pictures docs/section-${name}.svg and carries no <!-- rdc-section:${name} --> source block after it`);
    const rest = readme.slice(open, close).split('\n');
    const blank = rest.findIndex((l) => l.trim() === '');
    if (blank < 0) throw new Error(`plates: the rdc-section:${name} block has no blank line between its note and its source`);
    // The verify section draws the commands the rdc-verify:machine-readable
    // comment carries, the one copy checker/counts-sweep.mjs reads the guard
    // count from: a {{rdc-verify}} line in the source stands for that block.
    const lines = rest.slice(blank + 1).flatMap((l) => (l.trim() === '{{rdc-verify}}' ? ['```sh', ...verifyCommands(readme), '```'] : [l]));
    out[name] = { heading, lines };
  }
  return out;
}

// The command lines of the rdc-verify:machine-readable comment: every line
// of the block after its note that starts with a command, runs of spaces
// before the # comment collapsed to one.
export function verifyCommands(readme) {
  const open = readme.indexOf('<!-- rdc-verify:machine-readable');
  const close = open < 0 ? -1 : readme.indexOf('-->', open);
  if (open < 0 || close < 0) throw new Error('plates: the README carries no rdc-verify:machine-readable block');
  const lines = readme.slice(open, close).split('\n').slice(1).map((l) => l.trim()).filter((l) => /^(node |bash |rdc |npm )/.test(l));
  if (!lines.length) throw new Error('plates: the rdc-verify:machine-readable block carries no command line');
  return lines.map((l) => l.replace(/\s+#\s+/, ' # '));
}

export function renderSection(name, src, theme) {
  const t = THEMES[theme];
  const nodes = [];
  let y = 34;
  nodes.push(`<text x="${LEFT}" y="${y}" font-size="19" font-weight="600" fill="${t.text}">${esc(src.heading)}</text>`);
  y += 14;
  nodes.push(`<line x1="${LEFT}" y1="${y}" x2="${RIGHT}" y2="${y}" stroke="${t.rule}" stroke-width="1"/>`);
  y += 51;
  let code = false;
  let centre = false;
  let para = [];
  const line = (text, { size = 13.5, weight = '', mono = false, x = LEFT, anchor = '' } = {}) => {
    nodes.push(`<text x="${x}" y="${y}" font-size="${size}"${weight ? ` font-weight="${weight}"` : ''}${mono ? ` font-family="${MONO}"` : ''}${anchor ? ` text-anchor="${anchor}"` : ''} fill="${t.text}">${esc(text)}</text>`);
    y += 20;
  };
  const flush = () => {
    if (!para.length) return;
    const text = plain(para.join(' '));
    for (const l of wrap(text, WRAP)) {
      if (centre) line(l, { x: W / 2, anchor: 'middle' });
      else line(l);
    }
    para = [];
    y += 10;
  };
  for (const raw of src.lines) {
    const l = raw.replace(/\s+$/, '');
    if (/^```/.test(l)) { flush(); if (code) y += 10; code = !code; continue; }
    if (code) {
      wrap(l, WRAP_CODE).forEach((part, i) => line(part, { size: 12.5, mono: true, x: i ? INDENT : LEFT }));
      continue;
    }
    if (l.trim() === '') { flush(); continue; }
    if (/^<div align="center">/.test(l)) { flush(); centre = true; continue; }
    if (/^<\/div>/.test(l)) { flush(); centre = false; continue; }
    if (l === '---') { flush(); nodes.push(`<line x1="${LEFT}" y1="${y - 6}" x2="${RIGHT}" y2="${y - 6}" stroke="${t.rule}" stroke-width="1"/>`); y += 20; continue; }
    if (/^### /.test(l)) { flush(); y += 6; line(plain(l.slice(4)), { size: 15, weight: '600' }); y += 10; continue; }
    if (/^  /.test(l)) { flush(); line(plain(l), { x: INDENT }); continue; }
    para.push(l);
  }
  flush();
  return svg(y + 20, t.bg, t.section, nodes);
}

// The claims rows: the rdc-claims block's table, header and rule skipped,
// three cells a row.
export function claimRows(readme) {
  const open = readme.indexOf('<!-- rdc-claims:machine-readable');
  const close = open < 0 ? -1 : readme.indexOf('-->', open);
  if (open < 0 || close < 0) throw new Error('plates: the README carries no rdc-claims:machine-readable block');
  const rows = [];
  for (const raw of readme.slice(open, close).split('\n')) {
    const l = raw.trim();
    if (!l.startsWith('|') || /^\|\s*claim\s*\|/i.test(l) || /^\|\s*-{3,}/.test(l)) continue;
    const cells = l.split('|').slice(1, -1).map((c) => c.trim());
    if (cells.length !== 3) throw new Error(`plates: a claims row does not carry three cells: ${l.slice(0, 60)}`);
    rows.push({ claim: plain(cells[0]), instrument: plain(cells[1]), when: plain(cells[2]) });
  }
  return rows;
}

export function renderClaims(rows, theme) {
  const t = THEMES[theme];
  const nodes = [];
  nodes.push(`<text x="${LEFT}" y="32" font-size="19" font-weight="600" fill="${t.text}">What is claimed, and the instrument behind each claim</text>`);
  nodes.push(`<text x="${LEFT}" y="54" font-size="13" fill="${t.muted}">${rows.length} claims. Every one names a command you can run yourself.</text>`);
  nodes.push(`<line x1="${LEFT}" y1="62" x2="${RIGHT}" y2="62" stroke="${t.rule}" stroke-width="1"/>`);
  let y = 88;
  for (const r of rows) {
    for (const l of wrap(r.claim, WRAP_CLAIM)) { nodes.push(`<text x="${LEFT}" y="${y}" font-size="13" fill="${t.text}">${esc(l)}</text>`); y += 18; }
    y += 6;
    for (const l of wrap(r.instrument, WRAP_INSTRUMENT)) { nodes.push(`<text x="38" y="${y}" font-size="12" font-family="${MONO}" fill="${t.muted}">${esc(l)}</text>`); y += 18; }
    y -= 6;
    nodes.push(`<text x="${RIGHT}" y="${y}" font-size="11" fill="${t.muted}" text-anchor="end">${esc(r.when)}</text>`);
    y += 24;
  }
  return svg(y + 6, t.bg, t.claims, nodes);
}

// Every plate the README pictures, rendered from the README's own text.
export function targets(readme) {
  const out = {};
  const src = sources(readme);
  for (const name of SECTIONS) {
    if (!src[name]) throw new Error(`plates: the README does not picture docs/section-${name}.svg`);
    out[`docs/section-${name}.svg`] = renderSection(name, src[name], 'light');
    out[`docs/section-${name}-dark.svg`] = renderSection(name, src[name], 'dark');
  }
  const rows = claimRows(readme);
  out['docs/claims-map.svg'] = renderClaims(rows, 'light');
  out['docs/claims-map-dark.svg'] = renderClaims(rows, 'dark');
  return out;
}

export function check(root = ROOT, readme = readFileSync(join(root, 'README.md'), 'utf8')) {
  const want = targets(readme);
  const drifted = [];
  for (const [rel, text] of Object.entries(want)) {
    const p = join(root, rel);
    if (!existsSync(p) || readFileSync(p, 'utf8') !== text) drifted.push(rel);
  }
  return { count: Object.keys(want).length, drifted };
}

export function render(root = ROOT) {
  const want = targets(readFileSync(join(root, 'README.md'), 'utf8'));
  for (const [rel, text] of Object.entries(want)) writeFileSync(join(root, rel), text, 'utf8');
  return Object.keys(want);
}

const texts = (svgText) => [...svgText.matchAll(/<text[^>]*>([^<]*)<\/text>/g)].map((m) => m[1].replace(/&lt;/g, '<').replace(/&gt;/g, '>').replace(/&quot;/g, '"').replace(/&amp;/g, '&'));

export function controls() {
  let fail = 0;
  const say = (ok, text) => { console.log(`  ${ok ? 'PASS' : 'FAIL'} ${text}`); if (!ok) fail++; };
  const readme = readFileSync(join(ROOT, 'README.md'), 'utf8');
  const r0 = check(ROOT, readme);
  say(r0.drifted.length === 0 && r0.count === SECTIONS.length * 2 + 2, `the tree as it stands: ${r0.count} plates, ${r0.drifted.length} drifted${r0.drifted.length ? ` (${r0.drifted.join(', ')})` : ''}`);
  const planted = readme.replace(/the thirty-one Adiutor controls/, 'the thirty Adiutor controls');
  const r1 = check(ROOT, planted);
  say(planted !== readme && r1.drifted.length === 2 && r1.drifted.every((d) => /section-verify/.test(d)), `trip: a stale count planted in the verify source drifts both verify plates and nothing else: ${r1.drifted.join(', ') || 'nothing'}`);
  const rows = claimRows(readme);
  const block = readme.slice(readme.indexOf('<!-- rdc-claims:machine-readable'), readme.indexOf('-->', readme.indexOf('<!-- rdc-claims:machine-readable')));
  const counted = block.split('\n').filter((l) => /^\s*\| /.test(l) && !/^\s*\| claim \|/.test(l) && !/^\s*\|-{3,}/.test(l)).length;
  const light = renderClaims(rows, 'light');
  say(rows.length === counted && rows.length >= 20 && light.includes(`>${rows.length} claims. Every one names a command you can run yourself.<`), `the claims plate draws every row of the table and says how many: ${rows.length} rows, ${counted} counted by shape`);
  let refused = '';
  try { sources(readme.replace('<!-- rdc-section:where', '<!-- rdc-sectionx:where')); } catch (e) { refused = e.message; }
  say(/rdc-section:where/.test(refused) && /no <!-- rdc-section:where -->/.test(refused), `trip: a pictured section with no source block is refused by name: ${refused.slice(0, 80)}`);
  const one = renderSection('x', { heading: '## Escaped', lines: ['<!DOCTYPE x [', 'a "q" & b'] }, 'light');
  say(one.includes('&lt;!DOCTYPE x [') && one.includes('&quot;q&quot; &amp; b') && !one.includes('<!DOCTYPE x'), 'a source line with angle brackets, quotes and an ampersand arrives escaped in the plate');
  const all = targets(readme);
  const widest = Math.max(...Object.values(all).flatMap((s) => texts(s).map((x) => x.length)));
  say(widest <= WRAP_CODE, `no drawn line is wider than the code wrap of ${WRAP_CODE} characters: widest ${widest}`);
  const fenced = renderSection('x', { heading: '## Fence', lines: ['```sh', 'npm run gate', '```', 'after'] }, 'light');
  const ft = texts(fenced);
  say(ft.includes('npm run gate') && !ft.some((x) => /^```|^sh$/.test(x)) && /font-family="ui-monospace[^"]*" fill="#1a1d24">npm run gate</.test(fenced), 'a fenced block draws its lines in monospace and never draws the fence or its language');
  const l = all['docs/section-welcome.svg'];
  const d = all['docs/section-welcome-dark.svg'];
  say(texts(l).join('\n') === texts(d).join('\n') && d.includes('#0f1117') && d.includes('#d97757') && !d.includes('#ffffff'), 'the dark plate carries the same words as the light one under the dark palette');
  console.log(`plates controls: 8 run, ${fail} failing`);
  return fail === 0;
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const args = process.argv.slice(2);
  if (args.includes('--controls')) process.exit(controls() ? 0 : 1);
  if (args.includes('--check')) {
    const r = check();
    console.log(r.drifted.length ? `plates: ${r.drifted.length} of ${r.count} drifted: ${r.drifted.join(', ')}` : `plates: ${r.count} plates in step`);
    process.exit(r.drifted.length ? 1 : 0);
  }
  console.log(`plates: ${render().length} written`);
}
